# -*- coding: utf-8 -*-
"""Diarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qu7_uT-EfajwjRdaSDNd9VXbddu7rpCB
"""

# Commented out IPython magic to ensure Python compatibility.
! git clone https://github.com/m-bain/whisperX.git
# %cd whisperX
! pip install -e .

!apt-get install ffmpeg

import whisperx
import gc

device = "cuda"
audio_file = "/content/karthi_vijay2.mp3"
batch_size = 16
compute_type = "float16"

model = whisperx.load_model("large-v3", device, compute_type=compute_type)


audio = whisperx.load_audio(audio_file)
result = model.transcribe(audio, batch_size=batch_size)
print(result["segments"])

print(result)
result["segments"][0]['text']="வணக்கம் நான் கார்த்திகேயன், நண்பரிடமிருந்து அழைக்கிறேன். முகநூல் விளம்பரங்களின் அடிப்படையில் நீங்கள் அழைக்கிறீர்கள். உங்களிடம் கடை இருக்கிறதா? ஆம் அவர்கள் விளையாட்டு கருவிகளை வழங்குகிறார்கள். எத்தனை வருடங்களாக கடை உள்ளது? 5 வருடங்கள் சார்."

print(result)

model_a, metadata = whisperx.load_align_model(language_code=result["language"], device=device,model_name="akashsivanandan/wav2vec2-large-xls-r-300m-tamil-colab-final")
result = whisperx.align(result["segments"], model_a, metadata, audio, device, return_char_alignments=False)

print(result["segments"])

diarize_model = whisperx.DiarizationPipeline(use_auth_token="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",device=device)

diarize_segments = diarize_model(audio)
diarize_model(audio, min_speakers=2, max_speakers=2)

result = whisperx.assign_word_speakers(diarize_segments, result)
print(diarize_segments)
print(result["segments"])